# Generated by Django 3.2.5 on 2021-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0002_auto_20210725_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('post', models.TextField(max_length=300)),
                ('posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
