# Generated by Django 3.2.5 on 2021-07-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0007_auto_20210725_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
