# Generated by Django 3.2.5 on 2021-07-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0013_auto_20210725_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
