# Generated by Django 3.2.5 on 2021-07-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0017_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(max_length=1000),
        ),
    ]
