# Generated by Django 3.2.5 on 2021-07-26 13:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0019_auto_20210726_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neighbour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='neighbuor.neighbourhood'),
            preserve_default=False,
        ),
    ]
