# Generated by Django 3.2.5 on 2021-07-26 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0020_post_neighbour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policeinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_email', models.CharField(max_length=50)),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police', to='neighbuor.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='Healthinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=100)),
                ('facility_email', models.CharField(max_length=50)),
                ('neighbour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='neighbuor.neighbourhood')),
            ],
        ),
    ]
