# Generated by Django 3.2.5 on 2021-07-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0021_healthinfo_policeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='user',
        ),
    ]
