# Generated by Django 3.2.5 on 2021-07-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0022_remove_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthinfo',
            name='neighbour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health', to='neighbuor.neighbourhood'),
        ),
        migrations.AlterField(
            model_name='policeinfo',
            name='neighbour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='police', to='neighbuor.neighbourhood'),
        ),
    ]
