# Generated by Django 3.2.5 on 2021-07-26 15:34

import cloudinary.models
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbuor', '0024_alter_post_neighbour'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
